// 공통응답포맷 v2 §5 Exception Code 전수 이식
export const ErrorCode = {
  // COMMON
  COMMON_BAD_REQUEST: 'COMMON_BAD_REQUEST',
  COMMON_UNAUTHORIZED: 'COMMON_UNAUTHORIZED',
  COMMON_FORBIDDEN: 'COMMON_FORBIDDEN',
  COMMON_NOT_FOUND: 'COMMON_NOT_FOUND',
  COMMON_CONFLICT: 'COMMON_CONFLICT',
  COMMON_VALIDATION_FAILED: 'COMMON_VALIDATION_FAILED',
  COMMON_SERVER_ERROR: 'COMMON_SERVER_ERROR',
  COMMON_EXTERNAL_API_ERROR: 'COMMON_EXTERNAL_API_ERROR',
  COMMON_EXTERNAL_API_TIMEOUT: 'COMMON_EXTERNAL_API_TIMEOUT',
  COMMON_DUPLICATE_REQUEST: 'COMMON_DUPLICATE_REQUEST',

  // AUTH
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_UNSUPPORTED_PROVIDER: 'AUTH_UNSUPPORTED_PROVIDER',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',

  // USER
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_INVALID_PROFILE: 'USER_INVALID_PROFILE',
  USER_LOCATION_NOT_FOUND: 'USER_LOCATION_NOT_FOUND',

  // ONBOARD
  ONBOARD_NOT_COMPLETED: 'ONBOARD_NOT_COMPLETED',
  ONBOARD_ALREADY_COMPLETED: 'ONBOARD_ALREADY_COMPLETED',
  ONBOARD_STEP_NOT_ALLOWED: 'ONBOARD_STEP_NOT_ALLOWED',
  ONBOARD_SKIN_TYPE_REQUIRED: 'ONBOARD_SKIN_TYPE_REQUIRED',
  ONBOARD_SKIN_TYPE_CONFLICT: 'ONBOARD_SKIN_TYPE_CONFLICT',
  ONBOARD_HORMONE_NOT_APPLICABLE: 'ONBOARD_HORMONE_NOT_APPLICABLE',

  // WEATHER
  WEATHER_LOCATION_REQUIRED: 'WEATHER_LOCATION_REQUIRED',
  WEATHER_LOCATION_NOT_FOUND: 'WEATHER_LOCATION_NOT_FOUND',
  WEATHER_API_FAILED: 'WEATHER_API_FAILED',
  WEATHER_UV_API_FAILED: 'WEATHER_UV_API_FAILED',

  // RECORD
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  RECORD_INVALID_TIME_SLOT: 'RECORD_INVALID_TIME_SLOT',
  RECORD_INVALID_MONTH: 'RECORD_INVALID_MONTH',
  RECORD_FUTURE_DATE_NOT_ALLOWED: 'RECORD_FUTURE_DATE_NOT_ALLOWED',

  // PRODUCT
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_INGREDIENT_NOT_FOUND: 'PRODUCT_INGREDIENT_NOT_FOUND',
  PRODUCT_ALREADY_SAVED: 'PRODUCT_ALREADY_SAVED',
  PRODUCT_INVALID_KEYWORD: 'PRODUCT_INVALID_KEYWORD',

  // PRODUCT_RECORD
  PRODUCT_RECORD_NOT_FOUND: 'PRODUCT_RECORD_NOT_FOUND',
  PRODUCT_ALREADY_RECORDED_IN_SLOT: 'PRODUCT_ALREADY_RECORDED_IN_SLOT',
  PRODUCT_RECORD_EMPTY: 'PRODUCT_RECORD_EMPTY',
  PRODUCT_RECORD_LIMIT_EXCEEDED: 'PRODUCT_RECORD_LIMIT_EXCEEDED',
  PRODUCT_RECORD_NOT_EDITABLE: 'PRODUCT_RECORD_NOT_EDITABLE',
  PRODUCT_RECORD_SAVE_FAILED: 'PRODUCT_RECORD_SAVE_FAILED',

  // ROUTINE
  ROUTINE_NOT_FOUND: 'ROUTINE_NOT_FOUND',
  ROUTINE_EMPTY: 'ROUTINE_EMPTY',
  ROUTINE_TIME_SLOT_MISMATCH: 'ROUTINE_TIME_SLOT_MISMATCH',
  ROUTINE_PRODUCT_PARTIALLY_MISSING: 'ROUTINE_PRODUCT_PARTIALLY_MISSING',

  // SCAN
  SCAN_PRODUCT_NOT_DETECTED: 'SCAN_PRODUCT_NOT_DETECTED',
  SCAN_LOW_IMAGE_QUALITY: 'SCAN_LOW_IMAGE_QUALITY',
  SCAN_UNSUPPORTED_MODE: 'SCAN_UNSUPPORTED_MODE',
  SCAN_SERVICE_UNAVAILABLE: 'SCAN_SERVICE_UNAVAILABLE',

  // SKIN
  SKIN_RECORD_NOT_FOUND: 'SKIN_RECORD_NOT_FOUND',
  SKIN_ALREADY_RECORDED_IN_SLOT: 'SKIN_ALREADY_RECORDED_IN_SLOT',
  SKIN_FACE_NOT_DETECTED: 'SKIN_FACE_NOT_DETECTED',
  SKIN_IMAGE_INVALID_FORMAT: 'SKIN_IMAGE_INVALID_FORMAT',
  SKIN_IMAGE_TOO_LARGE: 'SKIN_IMAGE_TOO_LARGE',
  SKIN_IMAGE_UPLOAD_FAILED: 'SKIN_IMAGE_UPLOAD_FAILED',
  SKIN_ANALYSIS_FAILED: 'SKIN_ANALYSIS_FAILED',
  SKIN_ANALYSIS_TIMEOUT: 'SKIN_ANALYSIS_TIMEOUT',

  // ANALYSIS
  ANALYSIS_DATA_INSUFFICIENT: 'ANALYSIS_DATA_INSUFFICIENT',
  ANALYSIS_PROFILE_NOT_FOUND: 'ANALYSIS_PROFILE_NOT_FOUND',
  ANALYSIS_GENERATION_FAILED: 'ANALYSIS_GENERATION_FAILED',

  // CHECK
  CHECK_NOT_FOUND: 'CHECK_NOT_FOUND',
  CHECK_PRODUCT_NOT_FOUND: 'CHECK_PRODUCT_NOT_FOUND',
  CHECK_PROFILE_NOT_READY: 'CHECK_PROFILE_NOT_READY',
  CHECK_INGREDIENT_DATA_INSUFFICIENT: 'CHECK_INGREDIENT_DATA_INSUFFICIENT',
  CHECK_CALCULATION_FAILED: 'CHECK_CALCULATION_FAILED',

  // REPORT
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_INVALID_PERIOD: 'REPORT_INVALID_PERIOD',
  REPORT_DATA_INSUFFICIENT: 'REPORT_DATA_INSUFFICIENT',
  REPORT_INSIGHT_NOT_FOUND: 'REPORT_INSIGHT_NOT_FOUND',

  // PERMISSION — 클라이언트 전용. 서버는 절대 이 코드를 반환하지 않습니다 (OS 권한은 서버가 알 수 없음).
  CAMERA_PERMISSION_DENIED: 'CAMERA_PERMISSION_DENIED',
  LOCATION_PERMISSION_DENIED: 'LOCATION_PERMISSION_DENIED',
  NOTIFICATION_PERMISSION_DENIED: 'NOTIFICATION_PERMISSION_DENIED',
} as const;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

// 빈 상태 안내 코드 — 빨간 오류 UI 금지. 기록이 부족한 신규 사용자의 "정상" 상태입니다.
// Phase 7-A 수정: CHECK_INGREDIENT_DATA_INSUFFICIENT가 빠져 있었습니다. api_명세서.md
// CHECK-02 문서에 "두 409 코드 모두 빈 상태 안내로 처리한다"고 명시돼 있는데
// CHECK_PROFILE_NOT_READY만 들어가 있어서, 이대로면 성분 데이터 부족 케이스가
// ErrorState(빨간 UI)로 잘못 떴을 것입니다.
export const EMPTY_STATE_CODES: ErrorCode[] = [
  ErrorCode.ANALYSIS_DATA_INSUFFICIENT,
  ErrorCode.CHECK_PROFILE_NOT_READY,
  ErrorCode.CHECK_INGREDIENT_DATA_INSUFFICIENT,
  ErrorCode.REPORT_DATA_INSUFFICIENT,
];

// 무음 처리 — client.ts 인터셉터가 이미 처리하므로 화면에 노출하지 않음
export const SILENT_RETRY_CODES: ErrorCode[] = [ErrorCode.AUTH_TOKEN_EXPIRED];

// 강제 화면 이동이 필요한 코드
export const FORCE_NAVIGATE_CODES: Partial<Record<ErrorCode, string>> = {
  [ErrorCode.AUTH_REFRESH_TOKEN_EXPIRED]: 'Auth', // S-00
  [ErrorCode.WEATHER_LOCATION_REQUIRED]: 'LocationSettings', // S-24
};